spring.application.name=optimizador-envios-backend

# OpenRouteService
openrouteservice.api-key=YOUR_API_KEY_HERE

# Proveedores
proveedores.fedex.costo-base=10000
proveedores.fedex.precio-por-kg=5000
proveedores.fedex.precio-por-km=200
proveedores.fedex.km-por-dia=800

proveedores.dhl.costo-base=12000
proveedores.dhl.precio-por-kg=4500
proveedores.dhl.precio-por-km=250
proveedores.dhl.km-por-dia=900

proveedores.local.costo-base=8000
proveedores.local.precio-por-kg=4000
proveedores.local.precio-por-km=150
proveedores.local.km-por-dia=600

