ALTER TABLE confirmaciones_pedido
    ADD COLUMN IF NOT EXISTS user_id VARCHAR(255);

ALTER TABLE confirmaciones_pedido
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
